### ISSUE TITLE
CloudflareTurnstile.invisible baseUrl is missing from Web

### ISSUE THREAD

**Issue by MattyBoy4444** [Nika0000/cloudflare_turnstile#27]
Just a quick note: baseUrl parameter is missing from CloudflareTurnstile.invisible web.

**Comment by Nika0000** [comment]
Hi, @MattyBoy4444
The `baseUrl` is only used on Android and iOS. On Web, it's not needed and has no effect, the browser already knows the current URL via `window.location.href`, which is basically what `baseUrl` represents on mobile.

If you're testing locally on web, make sure to add something like `http://localhost` to your Turnstile domain list in the Cloudflare dashboard, that’ll let it work properly during local dev.

**Comment by MattyBoy4444** [comment]
I understand but you can't build for Android/iOS and Web without doing imports for different platforms.  It would be nice to have one interface that works for all and it just ignores on the web.  That is how the widget works.

**Comment by Nika0000** [comment]
So, before the next featured release, I’ve included the fix in the [feature/js-to-web-migration](https://github.com/Nika0000/cloudflare_turnstile/tree/feature/js-to-web-migration) branch.

```yml
cloudflare_turnstile:
  git:
    url: https://github.com/Nika0000/cloudflare_turnstile.git
    ref: feature/js-to-web-migration
```
